[versions]
android-activity = "1.10.1"
android-gradle-plugin = "8.7.3"
android-api = "35"
android-datastore = "1.1.4"
android-paparazzi = "1.3.5"
android-test-junit = "1.7.8"
android-test-leak-canary = "2.14"
android-test-navigation = "2.8.9"
detekt-api = "1.23.8"
detekt-compose = "0.4.22"
detekt-formatting = "1.23.8"
jvm-api = "17"
jvm-bcrypt = "0.10.2"
jvm-logback = "1.5.16"
jvm-test-rebugger = "1.0.0-rc03"
kmp-kotlin-api = "2.1.10"
kmp-atomicfu = "0.27.0"
kmp-compose = "1.7.3"
kmp-coroutines = "1.10.1"
kmp-koin = "4.0.2"
kmp-date-time = "0.6.1"
kmp-ktor = "3.1.1"
kmp-navigation = "2.8.0-alpha10"
kmp-viewModel = "2.8.3"
kmp-test-turbine = "1.1.0"
kmp-buildconfig = "0.16.0"
kmp-immutable = "0.3.8"
kmp-window-classes = "0.5.0"
kmp-serialization = "1.8.0"
chamaleon = "1.0.10"

[libraries]
android-activity = { module = "androidx.activity:activity-compose", version.ref = "android-activity" }
android-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "android-datastore" }
android-paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "android-paparazzi" }
android-test-leak-canary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "android-test-leak-canary" }
android-test-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "android-test-navigation" }
android-test-junit = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "android-test-junit" }
android-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "android-test-junit" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt-api" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt-formatting" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt-api" }
gradle-kmp-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kmp-kotlin-api" }
gradle-kmp-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "kmp-compose" }
gradle-kmp-ktor = { module = "io.ktor.plugin:plugin", version.ref = "kmp-ktor" }
gradle-android-application = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android-gradle-plugin" }
gradle-android-library = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "android-gradle-plugin" }
gradle-chamaleon = { module = "io.github.gerardorodriguezdev.chamaleon:gradle-plugin", version.ref = "chamaleon" }
gradle-jvm-chamaleon = { module = "io.github.gerardorodriguezdev.chamaleon:chamaleon-core", version.ref = "chamaleon" }
gradle-kmp-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kmp-serialization" }
jvm-bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "jvm-bcrypt" }
jvm-ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "kmp-ktor" }
jvm-ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "kmp-ktor" }
jvm-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "jvm-logback" }
jvm-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kmp-kotlin-api" }
kmp-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kmp-coroutines" }
kmp-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kmp-atomicfu" }
kmp-koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "kmp-koin" }
kmp-koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "kmp-koin" }
kmp-koin-core = { module = "io.insert-koin:koin-core", version.ref = "kmp-koin" }
kmp-koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel", version.ref = "kmp-koin" }
kmp-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kmp-date-time" }
kmp-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "kmp-navigation" }
kmp-viewModel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "kmp-viewModel" }
kmp-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kmp-immutable" }
kmp-window-classes = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "kmp-window-classes" }
kmp-ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "kmp-ktor" }
kmp-ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "kmp-ktor" }
kmp-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "kmp-ktor" }
kmp-ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "kmp-ktor" }
kmp-ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "kmp-ktor" }
kmp-ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "kmp-ktor" }
kmp-ktor-server-call-id = { module = "io.ktor:ktor-server-call-id", version.ref = "kmp-ktor" }
kmp-ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "kmp-ktor" }
kmp-ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "kmp-ktor" }
kmp-ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "kmp-ktor" }
kmp-ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "kmp-ktor" }
kmp-ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit", version.ref = "kmp-ktor" }
kmp-ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "kmp-ktor" }
kmp-ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "kmp-ktor" }
kmp-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kmp-kotlin-api" }
kmp-test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kmp-coroutines" }
kmp-test-ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "kmp-ktor" }
kmp-test-koin = { module = "io.insert-koin:koin-test", version.ref = "kmp-koin" }
kmp-test-ktor-server-host = { module = "io.ktor:ktor-server-test-host", version.ref = "kmp-ktor" }
kmp-test-turbine = { module = "app.cash.turbine:turbine", version.ref = "kmp-test-turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-paparazzi = { id = "app.cash.paparazzi", version.ref = "android-paparazzi" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt-api" }
chamaleon = { id = "io.github.gerardorodriguezdev.chamaleon", version.ref = "chamaleon" }
kmp-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kmp-atomicfu" }
kmp-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kmp-kotlin-api" }
kmp-compose-jetbrains = { id = "org.jetbrains.compose", version.ref = "kmp-compose" }
kmp-kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kmp-kotlin-api" }
kmp-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kmp-kotlin-api" }
kmp-build-config = { id = "com.codingfeline.buildkonfig", version.ref = "kmp-buildconfig" }
