name: Production Deploy Workflow

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action

      - name: Generate environment
        run: |
          ./gradlew :server:services:app:generateEnvironment -Pchamaleon.environment="production.jvm.properties[IMAGE_NAME=app-production,IMAGE_PORT=8080,IMAGE_TAG=${{ github.ref_name }}-${{ github.sha }},REGISTRY_LOCATION=ghcr.io/${{ github.repository }},REGISTRY_USERNAME=${{ github.actor }},REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }},PROTOCOL=1,HOST=1,DISABLE_RATE_LIMIT=false,USE_MEMORY_DATA_SOURCES=false,POSTGRES_USER=1,POSTGRES_PASSWORD=1,PGPORT=1,PGDATABASE=1,REDIS_URL=1,JWT_SECRET_SIGN_KEY=1,JWT_SECRET_ENCRYPTION_KEY=1,JWT_REALM=1,JWT_AUDIENCE=1,JWT_ISSUER=1]"

      - name: Select environment
        run: |
          ./gradlew :server:services:app:selectEnvironment -Pchamaleon.newSelectedEnvironment=production

      - name: Publish
        run: |
          ./gradlew :server:services:app:publishImage